Fix #268: added platform support to Catena 4802
mcci-catena/Catena-Arduino-Platform pull request #269
Opened 2020-12-08 11:18 UTC by dhineshkumarmcci

Added support to new board Catena 4802, changes done:
- added ReadVin() to read analog value
- added GUID for 4802 base
- added I2C expander to platform table
- updated version number to v0.19.10.0
- updated README with 4802 and version details
- added 4802 to class hierarchy diagram

2020-12-18 18:58 UTC, terrillmoore requested changes
Sorry ... the `#ifs` require that this be reworked. It's architecturally not permitted to add board-specific dependencies in higher-level include files. So this can't be merged as is.

The best policy is not ever to use `#if` unless there is no alternative due to the IDE limitations. That's not the case here; a combination of virtual methods and careful hierarchy will suffice.

2020-12-18 18:58 UTC, terrillmoore commented on .travis.yml
> + # *** TESTS FOR STM32L0 / Catena 4551. 46xx. 480x boards ****
This is duplicating a typo -- the '.' should have been a ',' in the first place. Let's fix this. If everything I find is cosmetic, I'll do it.

2020-12-18 18:58 UTC, terrillmoore commented on README.md
> +  - Fix [#268](https://github.com/mcci-catena/Catena-Arduino-Platform/issues/268): adds support to the new board Catena 4802 (version 0.19.10.0).
This is not a patch, as it's adding new features. Either we have to make this 0.19.0.40 (a non-Semantic-Version field) or this has to be v0.20.0.  It's easier if this is a pre-release, and we do a separate release ticket. So need to be 0.19.0.40.

Generally, you can never change *any* of the three standard semantic-version fields on a branch or PR.

2020-12-18 18:58 UTC, terrillmoore commented on src/Catena4802.h
> +#if defined(ARDUINO_MCCI_CATENA_4802)
This is a problem. It's already conditioned above, so this should not be needed. Please justify use of a conditional compile here.

2020-12-18 18:58 UTC, terrillmoore commented on src/Catena480x.h
> +		APIN_VIN_SENSE = A0,
Forbidden to have this kind of dependency in a higher level document. Must refactor.

2020-12-18 18:58 UTC, terrillmoore commented on src/Catena480x.h
> +#if defined(ARDUINO_MCCI_CATENA_4802)
Forbidden construct.

2020-12-18 18:58 UTC, terrillmoore commented on src/CatenaBase.h
> +#define CATENA_ARDUINO_PLATFORM_VERSION CATENA_ARDUINO_PLATFORM_VERSION_CALC(0, 19, 10, 0)      /* v0.19.10.0 */
See previous comment, this is not allowed for a branch.

2020-12-18 18:58 UTC, terrillmoore commented on src/CatenaStm32L0.h
> +#if defined(ARDUINO_MCCI_CATENA_4802)
Not permitted.

2020-12-18 18:58 UTC, terrillmoore commented on src/lib/stm32/catena480x/Catena4802_ReadVoltage.cpp
> +Catena4802::ReadVin(void) const
This is probably not going to work given that there are header file issues and refactoring will be needed.

2020-12-21 08:22 UTC, dhineshkumarmcci commented on src/Catena4802.h
> +#if defined(ARDUINO_MCCI_CATENA_4802)
This is added by mistake, and will be removing it.

2020-12-21 19:50 UTC, dhineshkumarmcci commented
made the suggested changes and tested build with example sketches. They compile successfully

2020-12-23 17:40 UTC, terrillmoore approved these changes
Looks good.

2020-12-23 17:40 UTC, merged